version: '3.2'

services:
  logstash:
    build:
      context: logstash/
      args:
        LOGSTASH_VERSION: '8.4.0'
    volumes:
      - type: bind
        source: ./logstash/conf.d/
        target: /usr/share/logstash/pipeline/
        read_only: true
      - type: bind
        source: ./logstash/config/
        target: /usr/share/logstash/config/
      - ./logstash/log/://usr/share/logstash/log/
    ports:
      - "5044:5044"
    expose:
      - "5044"
    networks:
      - logging
    depends_on:
      - elasticsearch
  couchdb:
    build: ./couchdb
    volumes:
      - ./couchdb/log:/var/log/couchdb/
    ports:
      - "5984:5984"
    environment: 
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password
    networks:
      - logging
    volumes:
      - type: bind
        source: ./couchdb/config/local.ini
        target: /usr/local/etc/couchdb/local.ini
      - ./couchdb/log/:/usr/local/var/log/couchdb
  initd:
    image: buildpack-deps:focal-curl
    command: "bash /init.sh"
    environment: 
      COUCHDB_URL: couchdb:5984
      COUCHDB_AUTH: admin:password
    volumes:
      - ./couchdb/config/init.sh:/init.sh
    depends_on:
      - couchdb
    networks:
      - logging
  filebeat:
    build:
      context: filebeat
      args:
        FILEBEAT_VERSION: '8.4.0'
    entrypoint: "filebeat -e -strict.perms=false"
    volumes:
      - ./filebeat/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./couchdb/log:/var/log/couchdb
    networks:
      - logging
    depends_on:
      - logstash
      - initd
    links:
      - logstash
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: '8.4.0'
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - ./elasticsearch/item:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: elastic
    networks:
      - logging

networks:
  logging:
    driver: bridge

volumes:
  elasticsearch:
